AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Neko Atsume API
Parameters:
  WordsBucketName:
    Type: String
  WordsBucketKey:
    Type: String
  CatsApiId:
    Type: String

Resources:
  ListCats:
  # Returns list of Neko Atsume cats and their attributes
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ListCats
      Handler: get_items.list_cats_handler
      Runtime: python3.7
      CodeUri: ./api
      Description: Returns list of Neko Atsume cats and their attributes
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
      Events:
        ListCatsAPI:
          # An API endpoint that responds to HTTP GET and returns all cats
          Type: Api
          Properties:
            Path: /cats
            Method: GET

  GetCatById:
  # Returns a given Neko Atsume cat from cat id or cat name
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetCatById
      Handler: get_items.get_cat_by_id_handler
      Runtime: python3.7
      CodeUri: ./api
      Description: Returns a given Neko Atsume cat from cat id or cat name
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
      Events:
        GetCatByIdAPI:
          # An API endpoint that responds to HTTP GET and returns cats by id or name
          Type: Api
          Properties:
            Path: /cats/{id}
            Method: GET
  
  ListGoodies:
  # Returns list of Neko Atsume goodies and their attributes
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ListGoodies
      Handler: get_items.list_goodies_handler
      Runtime: python3.7
      CodeUri: ./api
      Description: Returns list of Neko Atsume goodies and their attributes
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
      Events:
        ListCatsAPI:
          # An API endpoint that responds to HTTP GET and returns all goodies
          Type: Api
          Properties:
            Path: /goodies
            Method: GET

  GetGoodyById:
  # Returns a given Neko Atsume goody from goody id or goody name
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetCatById
      Handler: get_items.get_goodies_by_id_handler
      Runtime: python3.7
      CodeUri: ./api
      Description: Returns a given Neko Atsume goody from goody id or goody name
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
      Events:
        GetCatByIdAPI:
          # An API endpoint that responds to HTTP GET and returns goodies by id or name
          Type: Api
          Properties:
            Path: /goodies/{id}
            Method: GET
            
  setAPIGRateLimit:
    Type: AWS::ApiGateway::UsagePlan
    Properties: 
      ApiStages: 
        - ApiId: !Ref CatsApiId
          Stage: Prod
      Description: Set rate limit for API to 120 requests per minute
      Throttle: 
        RateLimit: 2