AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Neko Atsume API
Parameters:
  WordsBucketName:
    Type: String
  WordsBucketKey:
    Type: String

Resources:
  ListCats:
  # Returns list of Neko Atsume cats and their attributes
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ListCats
      Handler: cats.list_cats_handler
      Runtime: python3.7
      CodeUri: ./api
      Description: Returns list of Neko Atsume cats and their attributes
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
      Events:
        ListCatsAPI:
          # An API endpoint that responds to HTTP GET and returns all cats
          Type: Api
          Properties:
            Path: /api/cats
            Method: GET

  GetCatById:
  # Returns list of Neko Atsume cats and their attributes
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetCatById
      Handler: cats.get_cats_by_id_handler
      Runtime: python3.7
      CodeUri: ./api
      Description: Returns list of Neko Atsume cats and their attributes
      Timeout: 120
      Policies:
       - AWSLambdaExecute
      Environment:
        Variables:
          WORDS_BUCKET_NAME: !Ref WordsBucketName
          WORDS_BUCKET_KEY: !Ref WordsBucketKey
      Events:
        GetCatByIdAPI:
          # An API endpoint that responds to HTTP GET and returns cats by id
          Type: Api
          Properties:
            Path: /api/cats/{id}
            Method: GET